const express = require('express')
const { plansController } = require('./plansController')
const { userController } = require('./userController')
const { productController } = require('./productController')
const { signalsController } = require('./signalsController')
const { watchlistController } = require('./watchlistController')
const { subscriptionController } = require('./subscriptionController')
const { settingsController } = require('./settingsController')

const router = express.Router()

router.get('/products', productController.getAllProducts)
router.get('/products/:name', productController.getProductByName)
router.post('/products', productController.createProduct)
router.put('/products/:name', productController.updateProduct)
router.delete('/products/:name', productController.deleteProduct)

router.get('/plans', plansController.getAllPlans)
router.get('/plans/product/:productName', plansController.getPlansByProduct)
router.get('/plans/stats', plansController.getPlanStats)
router.get('/plans/:id', plansController.getPlanById)
router.post('/plans', plansController.createPlan)
router.put('/plans/:id', plansController.updatePlan)
router.delete('/plans/:id', plansController.deletePlan)

router.get('/signals', signalsController.getAllSignals)
router.get('/signals/stats', signalsController.getSignalStats)
router.get('/signals/:id', signalsController.getSignalById)
router.post('/signals', signalsController.createSignal)
router.put('/signals/:id', signalsController.updateSignal)
router.delete('/signals/:id', signalsController.deleteSignal)

router.post('/users/register', userController.registerUser)
router.post('/users/login', userController.loginUser)
router.post('/users/admin/login', userController.loginAdmin)
router.get('/users', userController.getAllUsers)
router.get('/users/stats', userController.getUserStats)
router.get('/users/:id', userController.getUserById)
router.put('/users/:id', userController.updateUser)
router.delete('/users/:id', userController.deleteUser)
router.put('/users/:id/change-password', userController.changePassword)

router.get('/subscriptions/pending', subscriptionController.getPendingSubscriptions)
router.put('/subscriptions/:id/approve', subscriptionController.approveSubscription)
router.put('/subscriptions/:id/reject', subscriptionController.rejectSubscription)
router.get('/subscriptions/my', subscriptionController.getMySubscriptions)
router.get('/subscriptions', subscriptionController.getSubscriptions)
router.post('/subscriptions', subscriptionController.createSubscription)
router.get('/subscriptions/:id', subscriptionController.getSubscriptionById)
router.put('/subscriptions/:id', subscriptionController.updateSubscription)
router.delete('/subscriptions/:id', subscriptionController.deleteSubscription)

// Settings
router.get('/settings', settingsController.getSettings)
router.put('/settings', settingsController.updateSettings)
router.post('/settings/reset', settingsController.resetSettings)

module.exports = router
// Watchlist
router.get('/watchlist', watchlistController.getAll)
router.get('/watchlist/:id', watchlistController.getById)
router.post('/watchlist', watchlistController.create)
router.put('/watchlist/:id', watchlistController.update)
router.delete('/watchlist/:id', watchlistController.remove)
